[build]
#  publish = "exampleSite/public"
#  command = "cd exampleSite && hugo --minify --gc --themesDir ../.."
#  publish = "exampleSite/public"
#  command = "cd exampleSite && hugo --gc --themesDir ../.."
command = "hugo"
publish = "public"

[build.environment]
#  HUGO_VERSION = "0.80.0"
#  HUGO_THEME = "repo"
#  HUGO_VERSION = "0.60.1"
HUGO_VERSION = "v0.83.1"
HUGO_THEME = "copper-hugo"
HUGO_BASEURL = "roswellinfographics.com"
